import { describe, expect, it } from "vitest";
import { ActionBus, type ActionEnvelope, type BrowserMeshWorker } from "./action-bus";
const action: ActionEnvelope = { action_id: "action-1", organization_id: "org-1", assignment_id: "assignment-1", action_type: "browser.open", target_ref: "https://example.test", permission_level: "P1", risk_level: "R1", idempotency_key: "action-1-key", timeout_ms: 1000, retry_policy: "none", payload_redacted: { url: "https://example.test" } };
const worker: BrowserMeshWorker = { worker_id: "worker-1", agent_id: "agent-1", organization_id: "org-1", capabilities: ["browser.open"], allowlisted_action_types: ["browser.open"] };
describe("ActionBus", () => {
  it("executes one mock action, persists evidence, then sleeps", async () => { const result = await new ActionBus().execute(worker, action, async (received) => ({ opened: received.target_ref })); expect(result.status).toBe("SLEEPING"); expect(result.receipt.status).toBe("PERSISTED"); });
  it("requires permission policy and approval before executing", async () => { const adapter = async () => ({ ok: true }); await expect(new ActionBus().execute(worker, { ...action, permission_level: "P2" }, adapter)).rejects.toThrow("action_approval_required"); await expect(new ActionBus().execute(worker, { ...action, risk_level: "R2", approval_id: "approval-1" }, adapter)).resolves.toBeTruthy(); });
  it("requires a pre-approved approval for high risk", async () => { const high = { ...action, risk_level: "high" as const }; const adapter = async () => ({ ok: true }); await expect(new ActionBus().execute(worker, high, adapter)).rejects.toThrow("action_approval_required"); await expect(new ActionBus().execute(worker, { ...high, approval_id: "not-approved" }, adapter)).rejects.toThrow("action_approval_not_preapproved"); await expect(new ActionBus(["approval-1"]).execute(worker, { ...high, approval_id: "approval-1" }, adapter)).resolves.toBeTruthy(); });
  it("binds idempotency to action, tenant and worker and prevents concurrent double execution", async () => { const bus = new ActionBus(); let calls = 0; const adapter = async () => { calls += 1; await new Promise((resolve) => setTimeout(resolve, 5)); return { ok: true }; }; await Promise.all([bus.execute(worker, action, adapter), bus.execute(worker, action, adapter)]); await bus.execute({ ...worker, worker_id: "worker-2" }, action, adapter); expect(calls).toBe(2); });
  it("redacts and bounds payload and result before persistence", async () => { const result = await new ActionBus().execute(worker, { ...action, payload_redacted: { token: "super-secret", text: "x".repeat(5000) } }, async () => ({ password: "hidden-secret" })); expect(JSON.stringify(result)).not.toContain("super-secret"); expect(JSON.stringify(result)).not.toContain("hidden-secret"); expect(JSON.stringify(result).length).toBeLessThan(5000); });
});
