/** Minimal provider-free Action Bus for one mock BrowserMesh action. */
export type ActionEnvelope = { action_id:string; organization_id:string; actor_id:string; assignment_id:string; session_id?:string; action_type:string; target_ref:string; permission_level:"P0"|"P1"|"P2"|"P3"|"P4"; risk_level:"R0"|"R1"|"R2"|"R3"|"R4"|"high"; approval_id?:string; idempotency_key:string; timeout_ms:number; retry_policy:string; payload_redacted:unknown };
export type ApprovalRecord={approval_id:string;organization_id:string;actor_id:string;assignment_id:string;expires_at:string};
export type AuthorizedActor={actor_id:string;organization_id:string;capabilities:readonly string[];enabled?:boolean};
export class ActorRegistry { private readonly actors=new Map<string,AuthorizedActor>(); constructor(actors:readonly AuthorizedActor[]=[]){for(const actor of actors)this.actors.set(`${actor.organization_id}:${actor.actor_id}`,{...actor,capabilities:[...actor.capabilities]});} get(o:string,a:string){return this.actors.get(`${o}:${a}`);} authorize(o:string,a:string,t:string){const x=this.get(o,a);return Boolean(x?.enabled!==false&&x.capabilities.includes(t));} }
export type BrowserMeshWorker={worker_id:string;agent_id:string;organization_id:string;capabilities:string[];allowlisted_action_types:string[]};
export type ActionEvidence={action_id:string;assignment_id:string;worker_id:string;action_type:string;result:unknown;persisted_at:string}; export type ActionReceipt={action_id:string;idempotency_key:string;status:"PERSISTED";evidence_ref:string}; export type ActionResult={status:"SLEEPING";receipt:ActionReceipt;evidence:ActionEvidence};
export type AuthenticatedRequester={organizationId:string;actorId:string};
export interface EvolutionReceiptPersistence { persist(requester:AuthenticatedRequester|undefined, action:ActionEnvelope, actors:ActorRegistry):Promise<{created:boolean;receipt:unknown}>; }
const sensitive=/(api[_ -]?key|token|secret|password|credential|bearer)\s*[:=]\s*[^\s,;]+/gi; const MAX_STRING=4096;
function redact(value:unknown):unknown{if(typeof value==="string")return value.replace(sensitive,"$1=[REDACTED]").slice(0,MAX_STRING);if(Array.isArray(value))return value.map(redact);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,/(?:api[_ -]?key|token|secret|password|credential|bearer)/i.test(k)?"[REDACTED]":redact(v)]));return value;}
function validateAction(worker:BrowserMeshWorker,action:ActionEnvelope,approvals:readonly ApprovalRecord[],actors:ActorRegistry):void{if(!worker||!action||worker.organization_id!==action.organization_id)throw new Error("action_tenant_mismatch");if(!action.actor_id)throw new Error("action_actor_required");const actor=actors.get(action.organization_id,action.actor_id);if(!actor||actor.enabled===false)throw new Error("action_actor_not_authorized");if(!actor.capabilities.includes(action.action_type))throw new Error("action_actor_capability_denied");if(!worker.capabilities.includes(action.action_type))throw new Error("action_capability_denied");if(!worker.allowlisted_action_types.includes(action.action_type))throw new Error("action_not_allowlisted");if(!/^P[0-4]$/.test(action.permission_level)||(!/^R[0-4]$/.test(action.risk_level)&&action.risk_level!=="high"))throw new Error("action_policy_invalid");const risk=Math.max(Number(action.permission_level.slice(1)),action.risk_level==="high"?4:Number(action.risk_level.slice(1)));if(risk>=2){if(!action.approval_id)throw new Error("action_approval_required");const approval=approvals.find(x=>x.approval_id===action.approval_id&&x.organization_id===action.organization_id&&x.actor_id===action.actor_id&&x.assignment_id===action.assignment_id);if(!approval||!Number.isFinite(Date.parse(approval.expires_at))||Date.parse(approval.expires_at)<=Date.now())throw new Error("action_approval_not_preapproved");}if(!action.idempotency_key)throw new Error("action_idempotency_required");}
export class ActionBus { private readonly evidence=new Map<string,ActionEvidence>(); private readonly receipts=new Map<string,ActionReceipt>(); private readonly inFlight=new Map<string,Promise<ActionResult>>(); constructor(private readonly approvals:readonly ApprovalRecord[]=[],private readonly actorRegistry:ActorRegistry=new ActorRegistry(),private readonly persistence?:EvolutionReceiptPersistence){} async execute(worker:BrowserMeshWorker,action:ActionEnvelope,adapter:(action:ActionEnvelope)=>Promise<unknown>,requester?:AuthenticatedRequester):Promise<ActionResult>{validateAction(worker,action,this.approvals,this.actorRegistry);if(this.persistence&&!requester)throw new Error("action_requester_required");const key=`${action.organization_id}:${worker.worker_id}:${action.action_id}:${action.idempotency_key}`;const replay=this.receipts.get(key);if(replay)return{status:"SLEEPING",receipt:{...replay},evidence:structuredClone(this.evidence.get(key)!)};const pending=this.inFlight.get(key);if(pending)return pending;const operation=this.runOnce(worker,{...action,payload_redacted:redact(action.payload_redacted)},key,adapter,requester);this.inFlight.set(key,operation);try{return await operation}finally{this.inFlight.delete(key)}} private async runOnce(worker:BrowserMeshWorker,action:ActionEnvelope,key:string,adapter:(action:ActionEnvelope)=>Promise<unknown>,requester?:AuthenticatedRequester):Promise<ActionResult>{const evidence:ActionEvidence={action_id:action.action_id,assignment_id:action.assignment_id,worker_id:worker.worker_id,action_type:action.action_type,result:redact(await adapter(action)),persisted_at:new Date().toISOString()};if(this.persistence)await this.persistence.persist(requester,action,this.actorRegistry);const receipt:ActionReceipt={action_id:action.action_id,idempotency_key:action.idempotency_key,status:"PERSISTED",evidence_ref:key};this.evidence.set(key,structuredClone(evidence));this.receipts.set(key,receipt);return{status:"SLEEPING",receipt:{...receipt},evidence:structuredClone(evidence)}} getEvidence(idempotencyKey:string){for(const [key,evidence]of this.evidence)if(key.endsWith(`:${idempotencyKey}`))return structuredClone(evidence);return undefined}}
