import { describe, expect, it } from "vitest";
import { ActionBus, ActorRegistry, type ActionEnvelope, type ApprovalRecord, type BrowserMeshWorker } from "./action-bus";
const action: ActionEnvelope = { action_id: "action-1", organization_id: "org-1", actor_id: "actor-1", assignment_id: "assignment-1", action_type: "browser.open", target_ref: "https://example.test", permission_level: "P1", risk_level: "R1", idempotency_key: "action-1-key", timeout_ms: 1000, retry_policy: "none", payload_redacted: { url: "https://example.test" } };
const worker: BrowserMeshWorker = { worker_id: "worker-1", agent_id: "agent-1", organization_id: "org-1", capabilities: ["browser.open"], allowlisted_action_types: ["browser.open"] };
const approval: ApprovalRecord = { approval_id: "approval-1", organization_id: "org-1", actor_id: "actor-1", assignment_id: "assignment-1", expires_at: "2099-01-01T00:00:00.000Z" };
const registry = new ActorRegistry([{ actor_id: "actor-1", organization_id: "org-1", capabilities: ["browser.open"] }]);
describe("ActionBus", () => {
  it("executes one real action, persists evidence, then sleeps", async () => { const result = await new ActionBus([], registry).execute(worker, action, async (received) => ({ opened: received.target_ref })); expect(result.status).toBe("SLEEPING"); expect(result.receipt.status).toBe("PERSISTED"); });
  it("rejects an actor that is only declared by the envelope", async () => { await expect(new ActionBus([], registry).execute(worker, { ...action, actor_id: "forged-actor" }, async () => ({ ok: true }))).rejects.toThrow("action_actor_not_authorized"); });
  it("rejects an authorized actor without the requested capability", async () => { const narrowRegistry = new ActorRegistry([{ actor_id: "actor-1", organization_id: "org-1", capabilities: ["browser.close"] }]); await expect(new ActionBus([], narrowRegistry).execute(worker, action, async () => ({ ok: true }))).rejects.toThrow("action_actor_capability_denied"); });
  it("requires contextual approval for medium risk", async () => { const adapter = async () => ({ ok: true }); const medium = { ...action, permission_level: "P2" as const, approval_id: "approval-1" }; await expect(new ActionBus([], registry).execute(worker, medium, adapter)).rejects.toThrow("action_approval_not_preapproved"); await expect(new ActionBus([approval], registry).execute(worker, medium, adapter)).resolves.toBeTruthy(); await expect(new ActionBus([{ ...approval, expires_at: "2000-01-01T00:00:00.000Z" }], registry).execute(worker, medium, adapter)).rejects.toThrow("action_approval_not_preapproved"); });
  it("requires contextual approval for high risk", async () => { const high = { ...action, risk_level: "high" as const, approval_id: "approval-1" }; const adapter = async () => ({ ok: true }); await expect(new ActionBus([approval], registry).execute({ ...worker, organization_id: "org-2" }, high, adapter)).rejects.toThrow("action_tenant_mismatch"); await expect(new ActionBus([approval], registry).execute(worker, { ...high, actor_id: "actor-2" }, adapter)).rejects.toThrow("action_actor_not_authorized"); await expect(new ActionBus([approval], registry).execute(worker, high, adapter)).resolves.toBeTruthy(); });
  it("binds idempotency to action, tenant and worker and prevents concurrent double execution", async () => { const bus = new ActionBus([], registry); let calls = 0; const adapter = async () => { calls += 1; await new Promise((resolve) => setTimeout(resolve, 5)); return { ok: true }; }; await Promise.all([bus.execute(worker, action, adapter), bus.execute(worker, action, adapter)]); await bus.execute({ ...worker, worker_id: "worker-2" }, action, adapter); expect(calls).toBe(2); });
  it("redacts and bounds payload and result before persistence", async () => { const result = await new ActionBus([], registry).execute(worker, { ...action, payload_redacted: { token: "super-secret", text: "x".repeat(5000) } }, async () => ({ password: "hidden-secret" })); expect(JSON.stringify(result)).not.toContain("super-secret"); expect(JSON.stringify(result)).not.toContain("hidden-secret"); expect(JSON.stringify(result).length).toBeLessThan(5000); });
});
