"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle, Clock, Sparkle } from "@/lib/ui/icons";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/empty/EmptyState";
import { OpportunityCard, type ContentOpportunity } from "@/components/content-os/OpportunityCard";

type ApiEnvelope<T> = { data?: T };

export function ContentOsOverview({ canManage }: { canManage: boolean }) {
  const [opportunities, setOpportunities] = useState<ContentOpportunity[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  useEffect(() => { let cancelled = false; void fetch("/api/v1/content-os/intelligence/opportunities?status=new", { credentials: "include" }).then((response) => response.ok ? response.json() as Promise<ApiEnvelope<ContentOpportunity[]>> : Promise.reject(new Error("request"))).then((payload) => { if (!cancelled) setOpportunities(Array.isArray(payload.data) ? payload.data : []); }).catch(() => { if (!cancelled) setError(true); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  const decide = async (id: string, status: "accepted" | "rejected") => { const response = await fetch("/api/v1/content-os/intelligence/opportunities", { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); if (response.ok) setOpportunities((items) => items.filter((item) => item.id !== id)); };
  const stats = [["A decidir", opportunities.length, Clock], ["Em produção", "—", Sparkle], ["Publicações próximas", "—", CheckCircle], ["Alertas", error ? "1" : "—", AlertTriangle]] as const;
  return <div className="space-y-8"><section className="grid grid-cols-2 gap-3 md:grid-cols-4">{stats.map(([label, value, Icon]) => <Card key={label}><CardContent className="flex items-center gap-3 p-4"><Icon size={20} className="text-muted-foreground" aria-hidden /><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div></CardContent></Card>)}</section><section className="space-y-4" aria-labelledby="opportunities-title"><div className="flex items-center justify-between gap-3"><div><h2 id="opportunities-title" className="text-lg font-semibold">Oportunidades a decidir</h2><p className="text-sm text-muted-foreground">Escolha quais sinais merecem virar conteúdo.</p></div><Button asChild variant="ghost" size="sm"><Link href="/app/content-os/radar">Abrir radar <ArrowRight size={15} aria-hidden /></Link></Button></div>{loading ? <div className="grid gap-4 md:grid-cols-2"><Card><CardContent className="h-36 animate-pulse p-6" /></Card><Card><CardContent className="h-36 animate-pulse p-6" /></Card></div> : error ? <Card><CardContent className="flex items-center gap-3 p-6"><AlertTriangle className="text-error" size={20} aria-hidden /><div><p className="font-medium">Não foi possível carregar o radar</p><p className="text-sm text-muted-foreground">Tente novamente em alguns instantes.</p></div></CardContent></Card> : opportunities.length === 0 ? <Card><EmptyState icon={Sparkle} headline="Nenhuma oportunidade pendente" subcopy="Quando encontrarmos um sinal relevante, ele aparece aqui para sua decisão." /></Card> : <div className="grid gap-4 md:grid-cols-2">{opportunities.slice(0, 6).map((opportunity) => <OpportunityCard key={opportunity.id} opportunity={opportunity} onDecision={canManage ? (status) => void decide(opportunity.id, status) : undefined} />)}</div>}</section><section className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>Fluxo editorial</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><div className="flex items-center gap-3"><Badge variant="secondary">1</Badge><span>Descubra sinais e concorrentes.</span></div><div className="flex items-center gap-3"><Badge variant="secondary">2</Badge><span>Decida o que merece atenção.</span></div><div className="flex items-center gap-3"><Badge variant="secondary">3</Badge><span>Crie, aprove e publique.</span></div></CardContent></Card><Card><CardHeader><CardTitle>Operação saudável</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Os estados de cada job ficam visíveis aqui. Falhas nunca somem silenciosamente.</CardContent></Card></section></div>;
}
