import { timingSafeEqual } from "node:crypto";
import { z } from "zod";
import { createAuthorizationCode, getClient, RELAY_RESOURCE, RELAY_SCOPE } from "@/lib/oauth/relay-store";
import { env } from "@/lib/env";
const query = z.object({ response_type: z.literal("code"), client_id: z.string().min(1), redirect_uri: z.string().url(), code_challenge: z.string().min(43).max(128), code_challenge_method: z.literal("S256"), state: z.string().optional(), resource: z.string().url().optional(), scope: z.string().optional() });
function equal(a: string, b: string): boolean { const x = Buffer.from(a); const y = Buffer.from(b); return x.length === y.length && timingSafeEqual(x, y); }
export async function GET(req: Request): Promise<Response> { const parsed = query.safeParse(Object.fromEntries(new URL(req.url).searchParams)); if (!parsed.success) return Response.json({ error: "invalid_request" }, { status: 400 }); const p = parsed.data; const c = await getClient(p.client_id); if (!c || !c.redirectUris.includes(p.redirect_uri)) return Response.json({ error: "invalid_client" }, { status: 400 }); const html = `<html><body><h1>Autorizar conector Lumenva</h1><p>Cliente: ${escapeHtml(c.clientName)}</p><p>Permissão: enviar notificações de e-mail para o WhatsApp configurado.</p><form method="post"><input type="hidden" name="${"request"}" value="${encodeURIComponent(JSON.stringify(p))}"><label>Senha de aprovação <input type="password" name="approval_secret" required></label><button type="submit">Aprovar</button></form></body></html>`; return new Response(html, { headers: { "content-type": "text/html; charset=utf-8" } }); }
export async function POST(req: Request): Promise<Response> { try { const bodyText = await req.text(); const form = new URLSearchParams(bodyText); const p = query.parse(JSON.parse(decodeURIComponent(String(form.get("request"))))); const c = await getClient(p.client_id); if (!c || !c.redirectUris.includes(p.redirect_uri) || !equal(String(form.get("approval_secret") || ""), env.MCP_RELAY_OAUTH_APPROVAL_SECRET)) return Response.json({ error: "access_denied" }, { status: 400 }); const code = await createAuthorizationCode({ clientId: p.client_id, redirectUri: p.redirect_uri, resource: p.resource || RELAY_RESOURCE, scope: RELAY_SCOPE, codeChallenge: p.code_challenge }); const location = new URL(p.redirect_uri); location.searchParams.set("code", code); if (p.state) location.searchParams.set("state", p.state); return Response.redirect(location, 302); } catch { return Response.json({ error: "invalid_request" }, { status: 400 }); } }
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] || c)); }
