import { describe, expect, it, vi } from "vitest";

import { createScenarioRuntimeCouncil } from "./runtime-council";

describe("createScenarioRuntimeCouncil", () => {
  it("degrades to deterministic bounded candidates when the configured model is unavailable", async () => {
    const callModel = vi.fn().mockRejectedValue(new Error("provider unavailable"));
    const council = createScenarioRuntimeCouncil({
      callModel,
      maxRuntimeMs: 5_000,
      maxTokens: 2_000,
      maxCostCents: 20,
    });

    const proposal = await council.propose({
      organizationId: "org-a",
      scenarioId: "scenario-a",
      question: "Should we change the price?",
      evidence: [],
      existingStrategies: [{
        id: "baseline",
        organizationId: "org-a",
        scenarioId: "scenario-a",
        name: "Baseline",
        description: "Current configuration",
        parameters: { price: 49 },
        isBaseline: true,
        source: "system",
        evidenceRefs: [],
      }],
      maxCandidates: 2,
    });

    expect(proposal.candidates).toHaveLength(2);
    expect(proposal.candidates.every((candidate) => candidate.parameters.scenarioIntensity !== undefined)).toBe(true);
    expect(proposal.memberProvenance.some((member) => member.status === "failed")).toBe(true);
    expect(proposal.memberProvenance.some((member) => member.memberId === "bounded-fallback" && member.status === "ok")).toBe(true);
  });

  it("keeps model output ahead of fallback while preserving both member provenance records", async () => {
    const callModel = vi.fn().mockResolvedValue({
      text: JSON.stringify({
        candidates: [{
          name: "Model candidate",
          description: "Generated by configured model",
          parameters: { price: 69 },
          assumptions: [],
          risks: [],
          evidenceRefs: [],
        }],
        disagreements: [],
        synthesis: "model synthesis",
      }),
      provider: "test-provider",
      model: "test-model",
      tokens: 100,
      costCents: 1,
    });
    const council = createScenarioRuntimeCouncil({ callModel, maxRuntimeMs: 5_000 });

    const proposal = await council.propose({
      organizationId: "org-a",
      scenarioId: "scenario-a",
      question: "test question",
      evidence: [],
      existingStrategies: [],
      maxCandidates: 2,
    });

    expect(proposal.candidates[0]?.name).toBe("Model candidate");
    expect(proposal.memberProvenance.map((member) => member.memberId)).toEqual(["org-default-model", "bounded-fallback"]);
  });
});
