[directories]
astetcdir => /opt/asterisk-v2/etc/asterisk
astmoddir => /opt/asterisk-v2/lib/asterisk/modules
astvarlibdir => /opt/asterisk-v2/var/lib/asterisk
astdbdir => /opt/asterisk-v2/var/lib/asterisk
astkeydir => /opt/asterisk-v2/var/lib/asterisk
astdatadir => /opt/asterisk-v2/var/lib/asterisk
astspooldir => /opt/asterisk-v2/var/spool/asterisk
astrundir => /opt/asterisk-v2/var/run/asterisk
astlogdir => /opt/asterisk-v2/var/log/asterisk
astsbindir => /opt/asterisk-v2/sbin
astcachedir => /opt/asterisk-v2/var/cache/asterisk
[options]
runuser = root
group = root
transmit_silence = yes
