import { describe, expect, it, vi } from "vitest";
import { createConnection, redactConnectionMetadata, reconcileConnection, type ConnectionRepository, type DistributionConnection } from "@/lib/content-os/distribution/connection-service";
import type { DistributionProvider } from "@/lib/content-os/providers/distribution";

const base: DistributionConnection = { id: "c1", organization_id: "o1", provider: "postiz", provider_connection_id: null, display_name: "LinkedIn", status: "pending", metadata: {}, last_error_code: null, last_error_at: null };
function repository(): ConnectionRepository { let row = { ...base }; return { list: vi.fn(async () => [row]), find: vi.fn(async (_o, id) => id === row.id ? row : null), create: vi.fn(async () => row), update: vi.fn(async (input) => { row = { ...row, ...(input.providerConnectionId !== undefined ? { provider_connection_id: input.providerConnectionId } : {}), ...(input.status ? { status: input.status } : {}), ...(input.lastErrorCode !== undefined ? { last_error_code: input.lastErrorCode } : {}) }; return row; }) }; }
function provider(overrides: Partial<DistributionProvider> = {}): DistributionProvider { return { provider: "postiz", connect: vi.fn(async () => ({ connectionId: "remote-1", redirectUrl: "https://provider.test/oauth" })), publish: vi.fn(), status: vi.fn(), metrics: vi.fn(), health: vi.fn(async () => ({ ok: true, checkedAt: new Date().toISOString() })), ...overrides }; }

describe("distribution connection service", () => {
  it("redacts credential-shaped metadata recursively", () => expect(redactConnectionMetadata({ label: "x", api_key: "secret", apiKey: "secret", refresh_token: "secret", nested: { token: "secret", keep: true } })).toEqual({ label: "x", nested: { keep: true } }));
  it("creates locally then activates with provider reference", async () => { const db = repository(); const result = await createConnection(db, { postiz: provider() }, { organizationId: "o1", provider: "postiz", displayName: "LinkedIn", metadata: { api_key: "never" } }); expect(result.connection.status).toBe("active"); expect(result.connection.provider_connection_id).toBe("remote-1"); expect(db.create).toHaveBeenCalledWith(expect.objectContaining({ organizationId: "o1", metadata: {} })); });
  it("keeps a safe failed connection when provider errors", async () => { const db = repository(); await expect(createConnection(db, { postiz: provider({ connect: vi.fn(async () => { throw new Error("upstream"); }) }) }, { organizationId: "o1", provider: "postiz", displayName: "LinkedIn" })).rejects.toMatchObject({ code: "connection_provider_error" }); expect((await db.find("o1", "c1"))?.status).toBe("failed"); });
  it("reconciles only within the requested tenant", async () => { const db = repository(); const row = await reconcileConnection(db, provider(), { organizationId: "o1", id: "c1" }); expect(row.organization_id).toBe("o1"); await expect(reconcileConnection(db, provider(), { organizationId: "other", id: "c1" })).rejects.toMatchObject({ code: "connection_invalid" }); });
});
