import { defineConfig } from "vitest/config";
import path from "node:path";

export default defineConfig({
  root: path.resolve(__dirname),
  test: {
    environment: "jsdom",
    maxWorkers: 1,
    testTimeout: 15_000,
    setupFiles: ["./tests/setup/vitest.setup.ts"],
    globals: true,
    coverage: { provider: "v8", reporter: ["text", "html"] },
    exclude: [
      "**/node_modules/**",
      ".next",
      "dist",
      ".claude/**",
      "tests/e2e/**",
      "tests/invariants/**",
      "tests/journeys/**",
      "apps/crm/tests/e2e/**",
      "apps/crm/tests/invariants/**",
      "apps/crm/tests/journeys/**",
      "**/.worktrees/**",
      "**/.claude/worktrees/**",
      "scratchpad-*/**",
      "apps/site/**",
      "workers/voice-worker/**",
      "scripts/*.test.mjs",
      "apps/crm/scripts/*.test.mjs",
      "**/*.integration.test.ts",
      "**/*.integration.test.mts",
      "**/*.integration.test.tsx",
      "**/*.real.integration.test.ts",
      "**/*.postgres.integration.test.ts",
      "**/*.rls.integration.test.ts",
      "**/scripts/check-harness-consistency.test.mjs",
      "**/workers/voice-pipecat-runtime/main.test.mjs",
      "**/workers/voice-worker/pending-outbound.test.mjs",
      "**/_stages.test.tsx",
      "**/_mapping.test.tsx",
      "**/TeamMembersClient.test.tsx",
      "**/snooze-button.test.tsx",
    ],
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "."),
      "pg": path.resolve(__dirname, "node_modules/pg"),
      "@lumenva/db/drizzle/client": path.resolve(__dirname, "../../packages/social-brain/db/src/drizzle/client.ts"),
    },
  },
});
